"""What MD's calls actually do, for the ones where the signature is not enough.

MD's bindings are pybind11 with no docstrings written, so ``md_api`` can report a call's
name, its overloads and their types, and nothing at all about what it means. That is the
gap this fills: a caller who searches for ``Simulate`` gets the signature *and* the fact
that it returns ``True`` for any argument, including the one that leaves the garment flat.

**These annotate, they never replace.** The live build is still the ground truth for what
exists and what it takes; a note is an observation attached to it, measured against
:data:`MEASURED_AGAINST` by building scenes in MD and reading them back. Every claim here
is written up at length in ``docs/md-conventions.md``.

Keys are exactly as ``md_api`` spells a call, ``module.Function``. A key naming something
this build does not expose is a typo or a call MD has renamed, and either way the note
would silently never appear -- ``tests/md_required/test_bridge_live.py`` fails on that
rather than letting it rot.

Kept deliberately short and only for calls where the obvious reading is wrong. This is not
a second copy of the documentation; it is the warning that arrives at the moment of use.
"""

from __future__ import annotations

#: The MD build every note below was measured against.
MEASURED_AGAINST = "2026.0.315"

#: ``module.Function`` -> what using it actually does.
NOTES: dict[str, str] = {
    # -- Simulation ------------------------------------------------------------------
    "utility_api.Simulate": (
        "Runs n solver steps and returns True for ANY n, including n=1, which leaves the "
        "garment flat and reports success. Steps accumulate across calls; a few hundred "
        "is a drape. Measure the scene, never the return value."
    ),
    "utility_api.SetSimulationQuality": (
        "Takes two ints, not one, matching GetSimulationQuality()."
    ),
    # -- Sewing ----------------------------------------------------------------------
    "pattern_api.AddSeamlinePairGroup": (
        "Returns False for a line or piece index that does not exist, but validates "
        "indices and not meaning: a seam joining a hem to a neckline is accepted and "
        "counted. Count what MD ended up with; the scene looking right is not evidence. "
        "Sewing an edge to itself raises a modal dialog, which freezes MD's main thread "
        "and with it this bridge."
    ),
    "pattern_api.GetSeamlinePairGroupListInPattern": (
        "Per-piece seam membership, which nothing else reports. Use it to find orphaned "
        "pieces and to check left/right symmetry by seam count."
    ),
    # -- Fabric and materials --------------------------------------------------------
    "fabric_api.GetFabricCount": (
        "Unreliable: answers 0 for a new project that has a fabric, and answered 4 for a "
        "scene with four, so 0 is not the tell. GetFabricStyleNameList() is the real "
        "count and carries the names."
    ),
    "fabric_api.GetFabricName": (
        "Past the end of the list this returns '' instead of raising, so it cannot be "
        "used to probe for fabrics a count is hiding -- an empty name reads as 'a fabric "
        "with no name' and invents materials that are not there."
    ),
    "fabric_api.AddFabric": (
        "Takes a file path to a .zfab, not a name. Handed a plain string it adds nothing, "
        "raises nothing and returns 0 -- indistinguishable from having added a fabric at "
        "index 0. Check GetFabricStyleNameList() afterwards."
    ),
    "fabric_api.SetFabricPBRMaterialBaseColor": (
        "DANGER: a side index of 1 ended the MD process outright -- no dialog, no "
        "traceback, unsaved scene lost. Side 0 is safe, and reads at side 1 are fine. "
        "Save before writing the second side, if at all."
    ),
    "fabric_api.AssignFabricToPattern": (
        "Takes three ints, not two. A call written against a two-argument shape is an "
        "arity mistake, which MD reports as a signature error."
    ),
    "pattern_api.SetPatternPieceFabricIndex": (
        "The readback agreeing is not evidence the surface rebound. Recolour the fabric "
        "and look. If a surface will not take any fabric, check it is a pattern piece at "
        "all: topstitch geometry is generated by MD, is reached by no fabric call, and at "
        "a large width reads as webbing lying on the garment."
    ),
    "pattern_api.ExportObjectBrowserMaterialsList": (
        "Despite the name it exports nothing and takes no path: it returns a short string "
        "listing the scene's fabrics and trims. ~160 characters for a four-fabric scene, "
        "and it matched what MD actually drew when the counters did not."
    ),
    "utility_api.GetTrimStyleCount": (
        "Answered 0 for a scene whose Object Browser listed two trims. Like "
        "GetFabricCount, not a counter to trust."
    ),
    # -- Seeing the scene ------------------------------------------------------------
    "utility_api.SetCamViewPoint": (
        "This is the one that moves the 3D camera -- use it, not SetViewPoint, to see "
        "the back of a garment. Follow with Refresh3DWindow before a snapshot."
    ),
    "utility_api.SetViewPoint": (
        "Does NOT move the camera; measured PNG-size spread 0.0% across every value. "
        "SetCamViewPoint(n) is the one that does."
    ),
    "utility_api.GetViewPoint": "Answers -1 whatever was set.",
    "export_api.ExportSnapshot3D": (
        "Never produces byte-identical PNGs, even for one unchanged scene at a fixed "
        "camera: 16 captures gave 16 digests and repeated Refresh3DWindow never "
        "converges. Never hash a snapshot to detect change -- compare the pictures."
    ),
    "export_api.ExportOBJ": (
        "Pass the ImportExportOption overload. The bare-path form ExportOBJ(path) gave no "
        "reply in 300s and wrote zero bytes on a scene the two-argument form exported in "
        "4.7s and 108MB. The exported group names also say what every surface really is, "
        "which is the fastest way to tell a pattern piece from generated geometry."
    ),
    # -- Destructive and one-way -----------------------------------------------------
    "utility_api.NewProject": (
        "Discards the open scene without asking, and MD's API has no undo anywhere. Save "
        "first."
    ),
    "pattern_api.SetPatternFreeze": (
        "Write-only: there is no getter anywhere in the six modules, so a script cannot "
        "record the freeze state it is about to change and cannot put it back. With no "
        "undo either, this is a one-way edit -- reload the project if it mattered."
    ),
    "pattern_api.SetPatternLayer": (
        "Simulation layers hold trims off the garment surface and are not a finishing "
        "state: pieces left on layers 1-4 read as straps and pockets floating, which "
        "looks like a sewing bug. The 3D window also colour-codes by layer, so it reads "
        "as a material bug too. Move finished trims to layer 0 and re-simulate."
    ),
    # -- Reading a scene back --------------------------------------------------------
    "pattern_api.GetPatternInputInformation": (
        "PointList[0] is a header, not a point. Skip it or every piece gains a phantom "
        "vertex."
    ),
    "pattern_api.GetPatternPieceSolidifyStrengthen": (
        "Not broken: 534070.75 is the value for 'never set'. All six setters round-trip."
    ),
    "utility_api.SetArrangementPosition": (
        "Does nothing. Swept over five values with an avatar loaded, the garment moved "
        "7.7mm against an expected 377."
    ),
    # -- Environment -----------------------------------------------------------------
    "utility_api.RegisterPythonScript": (
        "Declared -> bool, and answers False for every name and path when called from a "
        "script running inside another one -- which is what a call over this bridge "
        "always is. Register from a top-level Run in MD's Python Editor instead, and "
        "never record the False as success."
    ),
}


def note_for(call: str) -> str | None:
    """What is known about ``call``, or ``None`` if nothing is."""
    return NOTES.get(call)


def annotate(entries: list[dict]) -> list[dict]:
    """Attach a ``note`` to each entry that has one, in place, and return them.

    Entries MD reported are never dropped, reordered or altered otherwise: an annotation
    is added beside what the live build said, and calls with nothing measured stay exactly
    as they arrived.
    """
    for entry in entries:
        note = NOTES.get(entry.get("call", ""))
        if note:
            entry["note"] = note
    return entries
